import Link from "next/link";
import styleCalamardo from "./style.css"



export const metadata = {
  title: "Calamardo - HomePage",
  description: "Generated by Next.js",
  keywords: ["Calamardo"]
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="Contenedor">
        {children}
      </body>
    </html>
  );
}
